name: 'Favorite listing'
multiple: FALSE
category: 'Blog'
enabled: TRUE
fields:
  collection:
    type: json_api_collection
    label: 'JSON:API'
    options:
      '#required': TRUE
      '#default_value':
        id: "vactory_blog_favorite"
        resource: node--vactory_blog
        filters:
          - fields[node--vactory_blog]=drupal_internal__nid,path,title,field_blog_category,field_vactory_excerpt,field_blog_tags,field_vactory_media,is_flagged,has_flag
          - fields[taxonomy_term--vactory_blog_categories]=tid,name
          - fields[taxonomy_term--vactory_blog_tags]=tid,name
          - fields[media--image]=name,thumbnail
          - fields[file--image]=filename,uri
          - include=field_blog_category,field_blog_tags,field_vactory_media,field_vactory_media.thumbnail
          - page[offset]=0
          - page[limit]=9
          - filter[status][value]=1
          - "[vactory:flagged_nodes:vactory_blog]"
        cache_tags:
          - flaggging_list
        cache_contexts:
          - user
        vocabularies:
          vactory_blog_categories: vactory_blog_categories
          vactory_blog_tags: vactory_blog_tags