version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    commit-message: 
    prefix: "Composer" 
    include: "scope" 
    schedule:
      interval: "daily"
    target-branch: "3.x" 
    reviewers: 
      - Bahlaouane-Hamza
      - voidagency
