name: default
kind: pipeline
type: docker

steps:
  - name: code-analysis
    image: kytay/sonar-node-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
      use_node_version: 20.11.1
  - name: phpcs
    image: docker/compose:1.29.2
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    depends_on:
      - code-analysis
    commands:
      - echo $${DRONE_COMMIT}
      - docker build -f ./Dockerfile --build-arg COMMIT_ID=$${DRONE_COMMIT} -t vactory_starter_kit/build .
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
