name: "CountDown"
# multiple: true
category: "CountDown"
enabled: TRUE
fields:
  intro:
    type: text_format
    label: "Intro contenu libre"
    options:
      "#format": full_html
  date:
    type: datetime
    label: "date"
    options:
      "#required": TRUE
  link:
    type: url_extended
    label: "link"
