name: "CountDown"
# multiple: true
category: "CountDown"
enabled: TRUE
fields:
  intro:
    type: text_format
    label: "Intro contenu libre"
    options:
      "#format": full_html
  cars:
    type: number
    label: "cars"
    options:
      "#required": TRUE
  date:
    type: date
    label: "date"
    options:
      "#required": TRUE
  link:
    type: url_extended
    label: "link"
