name: 'Banner video'
multiple: FALSE
category: 'Banners'
enabled: TRUE
fields:
  group_banner:
    g_title: 'Banner'
    video:
      type: text
      label: "Cloudinary Video URL"
      options:
        '#description': 'Use Cloudinary url following this path: https://res.cloudinary.com/CLOUD_ID/video/upload/f_webm,q_auto/VIDEO_PATH.webm'
        '#required': TRUE
    image:
      type: image
      label: 'Mobile Image'
    show_image:
      type: checkbox
      label: "Show Mobile image in Mobile devices instead of the video"
  group_banner_title:
    g_title: 'Title'
    custom_title:
      type: text
      label: 'Custom Titre'
      options:
        '#description': 'Surcharger le titre de la page.'
    use_page_title:
      type: checkbox
      label: 'Afficher le titre de la page'
      options:
        '#description': 'Afficher le titre de la page actuelle. Si "Custom Titre" est utiliser, ce champs ne sera pas pris en considération.'
  group_banner_content:
    g_title: 'Contenu'
    use_breadcrumb:
      type: checkbox
      label: "Afficher Le fil d'Ariane"
    description:
      type: text_format
      label: 'Description'
      options:
        '#format': 'full_html'
        '#description': 'Afficher du contenu suplémentaire.'
