name: 'Sondage'
multiple: FALSE
category: 'Sondage'
enabled: TRUE
fields:
  collection:
    type: json_api_collection
    label: 'JSON:API'
    options:
      '#required': TRUE
      '#default_value':
        id: "vactory_sondage_df"
        resource: block_content--vactory_sondage
        filters:
          - page[offset]=0
          - page[limit]=1
        optional_filters:
          vactory_sondage: block_content