name: 'NL - Content Title, Description, CTA To Right & Image Left'
multiple: FALSE
category: 'NL Content'
enabled: TRUE
fields:
  title:
    type: text
    label: 'Titre'
  description:
    type: textarea
    label: 'Description'
  link:
    type: url_extended
    label: 'Lien'
  link_alt:
    type: text
    label: 'Titre Lien'
  image:
    type: image
    label: 'Image'
    options:
      '#required': TRUE
  image_alt:
    type: text
    label: 'Text alternatif'
