name: "Formulaire d'authentication"
multiple: FALSE
category: "Espace privé"
enabled: TRUE
fields:
  group_settings:
  g_title: "setting"
  emprunt:
    type: checkbox
    label: "Activer l'empreint/FaceID"
  title:
    type: text
    label: "Titre"
  intro:
    type: text_format
    label: "Introduction"
    options:
      "#format": "full_html"
